# Generated by Django 5.2 on 2025-04-12 06:15

import timeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattachment',
            name='file',
            field=models.FileField(upload_to='event_attachments/', validators=[timeline.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
