# Generated by Django 5.2 on 2025-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_eventattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='share_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
