# Generated by Django 5.2 on 2025-04-13 03:30

import django.db.models.deletion
import timeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_medicalprofile_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalevent',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to='voice_recordings/', validators=[timeline.models.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_reports/', validators=[timeline.models.validate_file_extension])),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reports', to='timeline.medicalevent')),
            ],
        ),
        migrations.AddField(
            model_name='medicalevent',
            name='reports',
            field=models.ManyToManyField(blank=True, to='timeline.eventreport'),
        ),
    ]
