# Generated by Django 5.2 on 2025-04-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_medicalevent_voice_recording_eventreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalevent',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='related_events', to='timeline.eventreport'),
        ),
        migrations.AlterField(
            model_name='medicalevent',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
