# Generated by Django 5.2 on 2025-04-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_alter_medicalevent_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalevent',
            name='generated_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-profile.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
