# Generated by Django 5.2 on 2025-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_medicalevent_generated_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalevent',
            name='consolidated_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
